services:
  - type: web
    name: noseguidores-api
    env: python
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn api:app"
    envVars:
      - key: PORT
        value: 10000

